### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/trees-assignment-bjornvoesten#1]
You did implement assignment three.

Could you describe how you would implement that feature?

**Comment by bjornvoesten** [comment]
Hoe ik het aantal bij zou houden is dan de vraag?

Hierbij zou ik bij de waarde ook het aantal toevoegen.
Dus in plaats van: 
      1
2

Wordt het dit:
      1:1
2:1

En als de waarde 1 dan nogmaals toegevoegd zou worden is dit het resultaat:
      1:2
2:1

**Comment by bjornvoesten** [comment]
@dvberkel

**Comment by dvberkel** [comment]
This looks good to me.

An other option is to make one of the comparison operators non-strict. I.e. `<=` instead of `<`.  This way nodes with the same value could appear in the tree. Depending on your use case this could be easier than keeping track of the number of elements.
